# Generated by Django 6.0.4 on 2026-05-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='absolute_truth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='police_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='witness',
            name='hidden_truth',
            field=models.TextField(blank=True, null=True),
        ),
    ]
