# Generated by Django 6.0.4 on 2026-06-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usercasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercasehistory',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
